SIMULATION = {'simulation': {'archetypes': {'spec': [
                                        {'lib': 'cyclus.pyagents', 'name': 'Source'},
                                        {'lib': 'cyclus.pyagents', 'name': 'Sink'},
                                        {'lib': 'cyclus.pyagents', 'name': 'NullRegion'},
                                        {'lib': 'cyclus.pyagents', 'name': 'NullInst'}
                                        ]},
                'control': {'duration': '100',
                            'solver': {'config': {'coin-or': {'timeout': '3599'}}},
                            'startmonth': '1',
                            'startyear': '2000'},
                'facility': [{'config': {'Source': {'capacity': '1.00',
                                                    'commod': 'commodity',
                                                    'recipe_name': 'commod_recipe'}},
                              'name': 'Source'},
                             {'config': {'Sink': {'capacity': '   1.00 ',
                                                  'in_commods': {'val': 'commodity'}}},
                              'name': 'Sink'}],
                'recipe': {'basis': 'mass',
                           'name': 'commod_recipe',
                           'nuclide': {'comp': '1', 'id': 'H1'}},
                'region': {'config': {'NullRegion': None},
                           'institution': {'config': {'NullInst': None},
                                           'initialfacilitylist': {'entry': [{'number': '1',
                                                                              'prototype': 'Source'},
                                                                             {'number': '1',
                                                                              'prototype': 'Sink'}]},
                                           'name': 'SingleInstitution'},
                           'name': 'SingleRegion'}}}
