
set(CYCLOPTS_ROOT_DIR $ENV{CYCLOPTS_ROOT_DIR})

FIND_PATH(CYCLOPTS_INCLUDE_DIR Variable.h
  HINTS ${CYCLOPTS_ROOT_DIR}/include
)

FIND_LIBRARY(CYCLOPTS_LIBRARY
  NAMES cyclopts libcyclopts
  HINTS ${CYCLOPTS_ROOT_DIR}/lib
)

# let us know if we found it
IF(CYCLOPTS_INCLUDE_DIR)
  MESSAGE("\tFound CYCLOPTS Include Dir: ${CYCLOPTS_INCLUDE_DIR}")
ELSE(CYCLOPTS_INCLUDE_DIR)
  MESSAGE("\tCYCLOPTS Include Dir NOT FOUND")
ENDIF(CYCLOPTS_INCLUDE_DIR)