// rec_backend.h
#ifndef CYCLUS_SRC_REC_BACKEND_H_
#define CYCLUS_SRC_REC_BACKEND_H_

#include <vector>

#include <boost/intrusive_ptr.hpp>

#include "datum.h"

namespace cyclus {

typedef std::vector<Datum*> DatumList;

/// An abstract base class for listeners (e.g. output databases) that want
/// to receive data generated by the simulation.
class RecBackend {
 public:
  virtual ~RecBackend() {};

  /// Used to pass a list of new/collected Datum objects
  virtual void Notify(DatumList data) = 0;

  /// Used to uniquely identify a backend - particularly if there are more
  /// than one in a simulation.
  virtual std::string Name() = 0;

  /// Flushes all buffered data in the backend to its final format/location.
  virtual void Flush() = 0;
};
} // namespace cyclus
#endif
