name: Housekeeping Checks

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Housekeeping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dependencies
        run: |
          sudo apt-get install -y clang-format

      - name: Housekeeping
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          find src/ \( -name "*.hpp" -o -name "*.cpp" -o -name "*.hh" -o -name "*.cc" -o -name "*.h" \) \
              -exec clang-format -style=file -i {} \;
          clang_diffs=`git status --porcelain`
          if [ -z "${clang_diffs}" ]; then
            echo -e "\033[32mStyle guide checker passed!\033[0m"
          else
            echo -e "\033[1;31mERROR: Style guide checker failed. Please run clang-format.\033[0m"
            echo -e "\033[33mclang_diffs: ${clang_diffs}\033[0m"
            git diff
            exit 1
          fi
